from backend.schemas.study import StudyResponse


class StudyService:

    @staticmethod
    def get_topic(subject: str, topic: str):

        study = StudyResponse(
            subject=subject,
            topic=topic,
            content=(
                f"This is the study material for "
                f"{topic} under {subject}.\n\n"
                "Currently this is mock content.\n"
                "Later it will be generated by the Teacher Agent."
            )
        )

        return {
            "success": True,
            "study": study.model_dump()
        }