"""Initial MentorAI schema

Revision ID: ff016e3bba01
Revises: 
Create Date: 2026-08-04 11:47:38.230508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff016e3bba01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    op.create_index(op.f('ix_achievements_achievement_id'), 'achievements', ['achievement_id'], unique=False)
    op.alter_column('learning_plans', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('learning_plans', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.create_index(op.f('ix_learning_plans_plan_id'), 'learning_plans', ['plan_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_index(op.f('ix_progress_progress_id'), 'progress', ['progress_id'], unique=False)
    op.alter_column('quiz_attempts', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_quiz_attempts_attempt_id'), 'quiz_attempts', ['attempt_id'], unique=False)
    op.alter_column('quiz_questions', 'option_a',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('quiz_questions', 'option_b',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('quiz_questions', 'option_c',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('quiz_questions', 'option_d',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('quiz_questions', 'correct_answer',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               nullable=False)
    op.create_index(op.f('ix_quiz_questions_question_id'), 'quiz_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_quizzes_quiz_id'), 'quizzes', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_id'), 'recommendations', ['recommendation_id'], unique=False)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=False)
    op.drop_column('students', 'last_login')
    op.create_index(op.f('ix_subjects_subject_id'), 'subjects', ['subject_id'], unique=False)
    op.create_index(op.f('ix_topics_topic_id'), 'topics', ['topic_id'], unique=False)
    op.drop_constraint(op.f('fk_subject'), 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'subjects', ['subject_id'], ['subject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subject'), 'topics', 'subjects', ['subject_id'], ['subject_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_topics_topic_id'), table_name='topics')
    op.drop_index(op.f('ix_subjects_subject_id'), table_name='subjects')
    op.add_column('students', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.alter_column('students', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_recommendations_recommendation_id'), table_name='recommendations')
    op.drop_index(op.f('ix_quizzes_quiz_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quiz_questions_question_id'), table_name='quiz_questions')
    op.alter_column('quiz_questions', 'correct_answer',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               nullable=True)
    op.alter_column('quiz_questions', 'option_d',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('quiz_questions', 'option_c',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('quiz_questions', 'option_b',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('quiz_questions', 'option_a',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_index(op.f('ix_quiz_attempts_attempt_id'), table_name='quiz_attempts')
    op.alter_column('quiz_attempts', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_progress_progress_id'), table_name='progress')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index(op.f('ix_learning_plans_plan_id'), table_name='learning_plans')
    op.alter_column('learning_plans', 'end_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('learning_plans', 'start_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index(op.f('ix_achievements_achievement_id'), table_name='achievements')
    op.create_table('goals',
    sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('fk_student')),
    sa.PrimaryKeyConstraint('goal_id', name=op.f('goals_pkey'))
    )
    # ### end Alembic commands ###
